'''
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding 
yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching 
teleportation; you can't help but try it for yourself and step onto the large 
yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; 
the only way out is the teleporter. Unfortunately, the teleporter seems to 
be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, 
and diagnostic equipment lying around. After connecting one of the diagnostic 
tools, it helpfully displays error code 0H-N0, which apparently means that 
there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). 
A tachyon beam enters the manifold at the location marked S; tachyon beams 
always move downward. Tachyon beams pass freely through empty space (.). 
However, if a tachyon beam encounters a splitter (^), the beam is stopped; 
instead, a new tachyon beam continues from the immediate left and from the 
immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) 
extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams 
are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

[...]

This process continues until all of the tachyon beams reach a splitter or 
exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting 
properties of the tachyon manifold. In this example, a tachyon beam is split a 
total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
'''
def printTree(rows):
    for row in rows:
        print(row)

def part1(rows):
    splits = 0

    for row in range(len(rows)):
        for pos in range(len(rows[row])):
            # manage the start
            if rows[row][pos] == 'S':
                selRow = rows[row + 1]
                newRow = selRow[:pos] + '|' + selRow[pos + 1:]
                rows[row + 1] = newRow
                continue
            
            if row > 0:
                # just flowing
                if rows[row][pos] == '.' and rows[row - 1][pos] == '|':
                    selRow = rows[row]
                    newRow = selRow[:pos] + '|' + selRow[pos + 1:]
                    rows[row] = newRow
                    continue

                # splitting
                if rows[row][pos] == '^' and rows[row - 1][pos] == '|':
                    splits += 1
                    selRow = rows[row]
                    newRow = selRow[:pos - 1] + '|' + selRow[pos] + '|' + selRow[pos + 2:]
                    rows[row] = newRow
                    continue
    
    printTree(rows)
    print(splits)

'''
--- Part Two ---
With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
'''
def part2(rows):
    splits = 0
    width = len(rows[0])
    counts = [[0 for _ in range(len(rows[0]))] for _ in range(len(rows))]

    for row in range(len(rows)):
        for pos in range(len(rows[row])):
            # manage the start
            if rows[row][pos] == 'S':
                selRow = rows[row + 1]
                newRow = selRow[:pos] + '|' + selRow[pos + 1:]
                counts[row + 1][pos] = 1
                rows[row + 1] = newRow
                continue
            
            # flow
            if row > 0 and rows[row - 1][pos] == '|':
                prev_count = counts[row - 1][pos]
                curr_char = rows[row][pos]

                if curr_char == '.' or curr_char == '|':
                    # normal flow without splits
                    counts[row][pos] += prev_count
                    rows[row] = rows[row][:pos] + '|' + rows[row][pos+1:]

                elif curr_char == '^':
                    # Split and sum from prev
                    # LX
                    if pos - 1 >= 0:
                        counts[row][pos - 1] += prev_count
                        rows[row] = rows[row][:pos - 1] + '|' + rows[row][pos:]
                    # RX
                    if pos + 1 < width:
                        counts[row][pos + 1] += prev_count
                        rows[row] = rows[row][:pos + 1] + '|' + rows[row][pos + 2:]
    
    splits = 0
    for x in counts[len(counts) - 1]:
        splits += x

    print("Result:", splits)

### Main starts here ###
part = 2
rows = []

with open('./2025/day7/input.txt', 'r') as f:
    for line in f:
        rows.append(line.strip())

if part == 1:
    part1(rows)

else:
    part2(rows)